"""remove patient user relation

Revision ID: 99993d81a84f
Revises: 395620683f54
Create Date: 2026-07-19 22:33:50.513272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99993d81a84f'
down_revision: Union[str, Sequence[str], None] = '395620683f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('uq_patients_user_id'), 'patients', type_='unique')
    op.drop_constraint(op.f('fk_patients_user'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_patients_user'), 'patients', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_patients_user_id'), 'patients', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'created_at')
    # ### end Alembic commands ###
